### ISSUE TITLE
Add to Quicklisp

### ISSUE THREAD

**Issue by EuAndreh** [DalekBaldwin/on-lisp#1]
Would you consider add the library to Quicklisp? How do you feel about that?

**Comment by EuAndreh** [comment]
I'd help support the library and add tests (and even integrate with [Travis CI](travis-ci.org)).
Just need to create an issue in the [Quicklisp projects repo](https://github.com/quicklisp/quicklisp-projects/issues).

**Comment by DalekBaldwin** [comment]
Yes, I was just thinking about how to adapt the tests for Travis. I think if we switched from lisp-unit to lisp-unit2, everything could be configured to use *debugger-hook* like your cl-slug library.

In the [distribution of the code](http://ep.yimg.com/ty/cdn/paulgraham/onlisp.lisp) linked from Paul Graham's site, it says this:

```
; This code is copyright 1993 by Paul Graham, but anyone who wants 
; to use the code in any nonprofit activity, or distribute free
; verbatim copies (including this notice), is encouraged to do so.
```

I assume he's cool with the various versions of his book other people have made available on the web, but since this is a substantial rewrite of the code, I'm going to ask his permission before I open a Quicklisp issue.

**Comment by DalekBaldwin** [comment]
All right, pg says it's okay. Do you want to go ahead and set things up for Travis? I suspect some of the trickier hacks might break on some Lisp implementations.

**Comment by DalekBaldwin** [comment]
I set up Travis and got most Lisps to build. I got the tests passing on CLISP too but it won't build on Travis until lisp-unit2 is updated with this: https://github.com/AccelerationNet/lisp-unit2/pull/3

I'll put in the request soon.

**Comment by EuAndreh** [comment]
Sorry for the absence, I was AFK for a while.

The travis is awesome, nice.

If you put the Quicklisp request now, it will only be available on February in the next release, together with the update of lisp-unit2. So there's no real problem on putting it right now.

Thanks for your attention =]

**Comment by DalekBaldwin** [comment]
Xach rejected it because of the nonprofit license, but I publicized it elsewhere. Thanks for the encouragement.
